lab_8.cpp
jennybamby/labs pull request #5
Opened 2018-12-18 18:47 UTC by jennybamby

2018-12-18 18:49 UTC, jennybamby commented
@nechaido Гюржи Евгения, ИП-82

2018-12-23 19:53 UTC, nechaido requested changes

2018-12-23 19:53 UTC, nechaido commented on lab_8.cpp
> +			for (int i = 0; i < ROW; i++)
Вывод лучше вынести в отдельную функцию, и вызыватьее в основной функции а не здесь.

2018-12-23 19:53 UTC, nechaido commented on lab_8.cpp
> +	int find_max_elements(int max, int **arr, int COL, int ROW, int max_ind)//поиск индекса столбца с максимальным элементом
Не нужно передавать `max` в таком виде, так как изминение локального значения, не приведет к изминению переменной, которая была передана в эту функцию.

2019-01-28 11:08 UTC, merged